# Generated by Django 5.1.4 on 2024-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe_name', models.CharField(max_length=100)),
                ('receipe_description', models.TextField()),
                ('receipe_Image', models.ImageField(upload_to='ReceipeImg')),
            ],
        ),
    ]
