# Generated by Django 5.1.4 on 2024-12-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciepe',
            old_name='reciepe_name',
            new_name='receipe_name',
        ),
    ]
