# Generated by Django 5.1.4 on 2024-12-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reso', '0002_rename_reciepe_name_reciepe_receipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciepe',
            new_name='Receipe',
        ),
    ]
